name: Raport Pogodowy co 3h

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie kodu repozytorium
        uses: actions/checkout@v4 # Zaktualizowano z v3

      - name: Instalacja Pythona
        uses: actions/setup-python@v5 # Zaktualizowano z v4
        with:
          python-version: '3.11'

      - name: Instalacja bibliotek
        run: pip install requests python-dotenv

      - name: Uruchomienie bota
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CITY: ${{ secrets.CITY }}
        run: python main.py